FROM balenalib/%%BALENA_ARCH%%-node:buster

# Install software packages
RUN install_packages \
  # X Dependencies
    xorg \
    x11vnc \
    xserver-xorg-video-all \
  # ElectronJS Dependencies
    clang \
    libnss3-dev \
    libgtk-3-dev \
    libnotify-dev \
    libasound2-dev \
    gnome-keyring

# Move to app dir
WORKDIR /usr/src/app

# Move app to filesystem
COPY ./app ./

# Install npm modules for the application
RUN npm install

# Start app
CMD bash start.sh
